import { DragnetConfig } from './dragnet-config.service';

export const DEFAULT_CONFIG: DragnetConfig = {
  sources: {
    twitter: {
      enabled: true,
      accounts: [
        'rightwingwatch',
        'hemantmehta',
        'ronfilipkowski',
        'NoKingsMovement',
        'NickJFuentes',
        'PastorLocke',
        'DougWilsonMoscow',
        'TuckerCarlson',
        'StevenLBannon',
        'RepMTG',
        'LauraLoomer',
        'RobertKennedyJr',
        'MattWalshBlog',
        'JackPosobiec',
        'PeteHegseth',
        'KCMMinistry',
        'LanceWallnau',
        'PastorJohnHagee',
        'ShaneDVaughn',
        'HankKunneman',
        'sandabortnow',
        'realstewpeters',
      ],
    },
    reddit: {
      enabled: true,
      subreddits: [
        'atheism',
        'exchristian',
        'exjw',
        'exmormon',
        'PoliticalVideo',
        'PublicFreakout',
        'Qult_Headquarters',
        'ParlerWatch',
        'politics',
        'WhitePeopleTwitter',
        'news',
        'worldnews',
        'LeopardsAteMyFace',
        'SelfAwarewolves',
        'PoliticalHumor',
        'Trumpvirus',
        'EyesOnIce',
        'Fuckthealtright',
        'MarchAgainstNazis',
        'ReligiousFruitcake',
      ],
      feedTypes: ['new', 'hot', 'top'],
      topTimeframe: 'week',
    },
    youtube: {
      enabled: true,
      channels: [
        { name: 'Right Wing Watch', channelId: 'UCMXqRHe8n1TX5iDvkLS62rw' },
      ],
    },
    tiktok: {
      enabled: false,
      accounts: [],
      hashtags: ['exvangelical', 'churchabuse', 'deconstruction'],
    },
    webRss: {
      enabled: true,
      feeds: [
        {
          name: 'Friendly Atheist',
          url: 'https://www.friendlyatheist.com/feed',
        },
        {
          name: 'Right Wing Watch',
          url: 'https://www.rightwingwatch.org/feed/',
        },
        {
          name: 'NPR Politics',
          url: 'https://feeds.npr.org/1014/rss.xml',
        },
        {
          name: 'Religion News Service',
          url: 'https://religionnews.com/feed/',
        },
        {
          name: 'Baptist News Global',
          url: 'https://baptistnews.com/feed/',
        },
        {
          name: 'BBC US & Canada',
          url: 'https://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml',
        },
      ],
    },
    redditSearch: { enabled: true },
    googleNews: { enabled: true },
    tiktokDiscovery: { enabled: true },
    instagramDiscovery: { enabled: true },
    substackDiscovery: { enabled: true },
    twitterDiscovery: { enabled: true },
  },
  scoring: {
    aiProvider: 'ollama',
    aiModel: 'cogito:70b',
    ollamaEndpoint: 'http://localhost:11434',
    batchSize: 30,
    editorialNotes: `JW/WATCHTOWER AUTO-BOOST: Any item mentioning Jehovah's Witnesses, Watchtower, governing body, disfellowshipping, shunning, kingdom hall, PIMO, or Bethel MUST receive a minimum score of 7. This is non-negotiable.
CHRISTIAN NATIONALISM PRIORITY: Mask-off moments from pastors, politicians, or media figures pushing theocracy should score high.
PROPHECY GRIFT: Failed predictions, seed-faith scams, and prosperity gospel hustles are always relevant.`,
    editorialVoice: '',
    targetClusterCount: 12,
    weights: {
      videoBoost: 2.0,
      figureBoosts: {
        top_priority: 3.0,
        high_priority: 2.0,
        monitor: 1.0,
      },
      recencyDecayDays: 7,
    },
  },
  subjects: [
    {
      id: 'christian_nationalism',
      label: 'Christian Nationalism',
      color: '#e74c3c',
      keywords: [
        'dominionism', 'theocracy', 'Christian nation',
        'separation of church', 'Ten Commandments', 'school prayer',
        'David Barton', 'Black Robe Regiment', 'school voucher',
        'Project Blitz', 'Seven Mountains', 'NAR',
        'New Apostolic Reformation',
      ],
      enabled: true,
      priority: 1,
    },
    {
      id: 'trump_authoritarianism',
      label: 'Trump / Authoritarianism',
      color: '#e67e22',
      keywords: [
        'MAGA', 'Trump', 'authoritarian', 'dictator', 'insurrection',
        'January 6', 'executive order', 'unitary executive',
        'Project 2025', 'Heritage Foundation', 'Schedule F',
      ],
      enabled: true,
      priority: 1,
    },
    {
      id: 'prophecy_grift',
      label: 'Prophecy / Grift',
      color: '#9b59b6',
      keywords: [
        'prophecy', 'prophetic', 'rapture', 'end times',
        'mark of the beast', 'tribulation', 'failed prediction',
        'prophet', 'sow a seed', 'seed faith', 'prosperity gospel',
        'anointing', 'miracle', 'divine healing',
      ],
      enabled: true,
      priority: 1,
    },
    {
      id: 'jw_watchtower',
      label: 'JW / Watchtower',
      color: '#3498db',
      keywords: [
        "Jehovah's Witness", 'Watchtower', 'governing body',
        'disfellowshipped', 'shunning', 'kingdom hall',
        'JW', 'PIMO', 'apostate', 'Bethel',
        'blood transfusion', 'two witness rule',
      ],
      enabled: true,
      priority: 1,
    },
    {
      id: 'white_nationalism',
      label: 'White Nationalism',
      color: '#c0392b',
      keywords: [
        'white nationalist', 'white supremacist', 'groyper',
        'great replacement', 'ethnostate', 'race realism',
        'alt-right', 'identitarian', 'white genocide',
      ],
      enabled: true,
      priority: 1,
    },
    {
      id: 'religious_abuse',
      label: 'Religious Abuse',
      color: '#8e44ad',
      keywords: [
        'clergy abuse', 'church abuse', 'sexual abuse',
        'cover up', 'spiritual abuse', 'purity culture',
        'complementarian', 'patriarchy', 'IBLP',
        'Bill Gothard', 'independent fundamental Baptist',
      ],
      enabled: true,
      priority: 1,
    },
    {
      id: 'science_denial',
      label: 'Science Denial',
      color: '#27ae60',
      keywords: [
        'flat earth', 'creationism', 'young earth',
        'anti-vax', 'climate denial', 'evolution denial',
        'intelligent design', 'Ken Ham', 'Answers in Genesis',
      ],
      enabled: true,
      priority: 2,
    },
    {
      id: 'media_manipulation',
      label: 'Media Manipulation',
      color: '#2980b9',
      keywords: [
        'fake news', 'propaganda', 'disinformation',
        'censorship', 'media bias', 'deplatform',
        'alternative media', 'citizen journalism',
      ],
      enabled: true,
      priority: 2,
    },
    {
      id: 'doge_dismantlement',
      label: 'DOGE / Dismantlement',
      color: '#f39c12',
      keywords: [
        'DOGE', 'government efficiency', 'dismantlement',
        'federal agencies', 'Elon Musk', 'Vivek Ramaswamy',
        'deregulation', 'deep state', 'administrative state',
      ],
      enabled: true,
      priority: 2,
    },
    {
      id: 'domestic_extremism',
      label: 'Domestic Extremism',
      color: '#d35400',
      keywords: [
        'militia', 'Proud Boys', 'Oath Keepers',
        'Three Percenter', 'Boogaloo', 'domestic terrorism',
        'sovereign citizen', 'extremist', 'radicalization',
      ],
      enabled: true,
      priority: 2,
    },
    {
      id: 'misogyny_submission',
      label: 'Misogyny / Submission',
      color: '#e91e63',
      keywords: [
        'submit', 'submission', 'complementarian',
        'biblical womanhood', 'Proverbs 31', 'headship',
        'tradwife', 'red pill', 'manosphere',
        'Andrew Tate', 'incel',
      ],
      enabled: true,
      priority: 2,
    },
    {
      id: 'race_civil_rights',
      label: 'Race / Civil Rights',
      color: '#795548',
      keywords: [
        'CRT', 'critical race theory', 'DEI',
        'affirmative action', 'civil rights', 'BLM',
        'racial justice', 'segregation', 'Jim Crow',
      ],
      enabled: true,
      priority: 2,
    },
    {
      id: 'ice_immigration',
      label: 'ICE / Immigration',
      color: '#607d8b',
      keywords: [
        'ICE', 'immigration', 'deportation', 'border',
        'asylum', 'refugee', 'illegal alien',
        'detention center', 'Tom Homan', 'mass deportation',
      ],
      enabled: true,
      priority: 2,
    },
    {
      id: 'iran_war_eschatology',
      label: 'Iran / War Eschatology',
      color: '#ff5722',
      keywords: [
        'Iran', 'Armageddon', 'end times war',
        'Gog and Magog', 'Israel', 'Temple Mount',
        'eschatology', 'Zionism', 'CUFI',
        'John Hagee', 'Christian Zionism',
      ],
      enabled: true,
      priority: 2,
    },
    {
      id: 'epstein',
      label: 'Epstein / Elite Networks',
      color: '#455a64',
      keywords: [
        'Epstein', 'Maxwell', 'trafficking',
        'Diddy', 'elite', 'cover-up',
        'blackmail', 'client list',
      ],
      enabled: true,
      priority: 3,
    },
  ],
  figures: [
    // Top Priority
    { name: 'Nick Fuentes', aliases: ['@NickJFuentes', 'Fuentes'], tier: 'top_priority', subjects: ['white_nationalism', 'christian_nationalism'] },
    { name: 'Joel Webbon', aliases: ['@JoelWebbon'], tier: 'top_priority', subjects: ['christian_nationalism', 'white_nationalism'] },
    { name: 'Greg Locke', aliases: ['@PastorLocke', 'Pastor Locke'], tier: 'top_priority', subjects: ['christian_nationalism', 'prophecy_grift'] },
    { name: 'Doug Wilson', aliases: ['@DougWilsonMoscow'], tier: 'top_priority', subjects: ['christian_nationalism', 'misogyny_submission'] },
    { name: 'Tucker Carlson', aliases: ['@TuckerCarlson'], tier: 'top_priority', subjects: ['trump_authoritarianism', 'media_manipulation'] },
    { name: 'Steve Bannon', aliases: ['@StevenLBannon', 'Bannon'], tier: 'top_priority', subjects: ['trump_authoritarianism', 'domestic_extremism'] },
    { name: 'Marjorie Taylor Greene', aliases: ['@RepMTG', 'MTG'], tier: 'top_priority', subjects: ['trump_authoritarianism', 'christian_nationalism'] },
    { name: 'Laura Loomer', aliases: ['@LauraLoomer'], tier: 'top_priority', subjects: ['trump_authoritarianism', 'domestic_extremism'] },
    { name: 'RFK Jr', aliases: ['@RobertKennedyJr', 'Robert F Kennedy'], tier: 'top_priority', subjects: ['science_denial', 'trump_authoritarianism'] },
    { name: 'Matt Walsh', aliases: ['@MattWalshBlog'], tier: 'top_priority', subjects: ['misogyny_submission', 'christian_nationalism'] },
    { name: 'Jack Posobiec', aliases: ['@JackPosobiec'], tier: 'top_priority', subjects: ['trump_authoritarianism', 'media_manipulation'] },
    { name: 'Pete Hegseth', aliases: ['@PeteHegseth'], tier: 'top_priority', subjects: ['christian_nationalism', 'trump_authoritarianism'] },
    { name: 'Kenneth Copeland', aliases: ['@KCMMinistry', 'Copeland'], tier: 'top_priority', subjects: ['prophecy_grift'] },
    { name: 'Lance Wallnau', aliases: ['@LanceWallnau'], tier: 'top_priority', subjects: ['christian_nationalism', 'prophecy_grift'] },
    { name: 'John Hagee', aliases: ['@PastorJohnHagee'], tier: 'top_priority', subjects: ['iran_war_eschatology', 'christian_nationalism'] },
    { name: 'Michele Bachmann', aliases: ['Bachmann'], tier: 'top_priority', subjects: ['christian_nationalism', 'trump_authoritarianism'] },

    // High Priority
    { name: 'Shane Vaughn', aliases: ['@ShaneDVaughn'], tier: 'high_priority', subjects: ['prophecy_grift', 'trump_authoritarianism'] },
    { name: 'Hank Kunneman', aliases: ['@HankKunneman'], tier: 'high_priority', subjects: ['prophecy_grift'] },
    { name: 'Kat Kerr', aliases: ['Kat Kerr'], tier: 'high_priority', subjects: ['prophecy_grift'] },
    { name: 'Steven Anderson', aliases: ['@sandabortnow', 'Pastor Anderson'], tier: 'high_priority', subjects: ['religious_abuse', 'christian_nationalism'] },
    { name: 'Kent Hovind', aliases: ['Hovind', 'Dr. Dino'], tier: 'high_priority', subjects: ['science_denial'] },
    { name: 'Stew Peters', aliases: ['@realstewpeters'], tier: 'high_priority', subjects: ['domestic_extremism', 'science_denial'] },
    { name: 'Andrew Tate', aliases: ['@Cobratate', 'Tate'], tier: 'high_priority', subjects: ['misogyny_submission'] },
    { name: 'Sneako', aliases: ['@sneaborern'], tier: 'high_priority', subjects: ['misogyny_submission'] },
    { name: 'Tom Homan', aliases: ['Homan'], tier: 'high_priority', subjects: ['ice_immigration'] },
    { name: 'Stephen Miller', aliases: ['Miller'], tier: 'high_priority', subjects: ['ice_immigration', 'trump_authoritarianism'] },
    { name: 'Kash Patel', aliases: ['Patel'], tier: 'high_priority', subjects: ['trump_authoritarianism'] },
    { name: 'Pam Bondi', aliases: ['Bondi'], tier: 'high_priority', subjects: ['trump_authoritarianism'] },
    { name: 'Seth Gruber', aliases: ['Gruber'], tier: 'high_priority', subjects: ['christian_nationalism'] },
    { name: 'Sean Feucht', aliases: ['@SeanFeucht'], tier: 'high_priority', subjects: ['christian_nationalism', 'prophecy_grift'] },
    { name: 'Dusty Deevers', aliases: ['Deevers'], tier: 'high_priority', subjects: ['christian_nationalism'] },
    { name: 'Nate Schatzline', aliases: ['Schatzline'], tier: 'high_priority', subjects: ['christian_nationalism'] },
    { name: 'Franklin Graham', aliases: ['@Franklin_Graham'], tier: 'high_priority', subjects: ['christian_nationalism'] },
    { name: 'Todd Chrisley', aliases: ['Chrisley'], tier: 'high_priority', subjects: ['prophecy_grift'] },
    { name: 'Erik Prince', aliases: ['Prince'], tier: 'high_priority', subjects: ['trump_authoritarianism'] },
    { name: 'Matt Schlapp', aliases: ['@maborschlapp'], tier: 'high_priority', subjects: ['trump_authoritarianism'] },
    { name: 'Bo French', aliases: ['French'], tier: 'high_priority', subjects: ['christian_nationalism'] },

    // Monitor
    { name: 'Julie Green', aliases: ['Julie Green Ministries'], tier: 'monitor', subjects: ['prophecy_grift'] },
    { name: 'Robin Bullock', aliases: ['Bullock'], tier: 'monitor', subjects: ['prophecy_grift'] },
    { name: 'Johnny Enlow', aliases: ['Enlow'], tier: 'monitor', subjects: ['prophecy_grift'] },
    { name: 'Kent Christmas', aliases: ['Christmas'], tier: 'monitor', subjects: ['prophecy_grift'] },
    { name: 'Jeff Jansen', aliases: ['Jansen'], tier: 'monitor', subjects: ['prophecy_grift'] },
    { name: 'Dale Partridge', aliases: ['Partridge'], tier: 'monitor', subjects: ['christian_nationalism'] },
    { name: 'Elijah Schaffer', aliases: ['Schaffer'], tier: 'monitor', subjects: ['christian_nationalism'] },
    { name: 'Lauren Witzke', aliases: ['Witzke'], tier: 'monitor', subjects: ['christian_nationalism', 'white_nationalism'] },
    { name: 'Vincent James', aliases: ['James'], tier: 'monitor', subjects: ['white_nationalism'] },
    { name: 'Ray Comfort', aliases: ['Comfort'], tier: 'monitor', subjects: ['science_denial'] },
    { name: 'Kirk Cameron', aliases: ['Cameron'], tier: 'monitor', subjects: ['christian_nationalism'] },
    { name: 'Jim Bakker', aliases: ['Bakker'], tier: 'monitor', subjects: ['prophecy_grift'] },
    { name: 'Jesse Duplantis', aliases: ['Duplantis'], tier: 'monitor', subjects: ['prophecy_grift'] },
    { name: 'Paula White', aliases: ['Paula White'], tier: 'monitor', subjects: ['prophecy_grift'] },
    { name: 'Peter Popoff', aliases: ['Popoff'], tier: 'monitor', subjects: ['prophecy_grift'] },
    { name: 'David Barton', aliases: ['Barton'], tier: 'monitor', subjects: ['christian_nationalism'] },
    { name: 'Ryan Walters', aliases: ['Walters'], tier: 'monitor', subjects: ['christian_nationalism'] },
  ],
  settings: {
    requestDelayMs: 500,
    maxResultsPerSource: 500,
    autoScanIntervalMinutes: 120,
    autoScanEnabled: false,
    maxItemAgeDays: 7,
    feedPageSize: 20,
    minScoreToShow: 1,
  },
};
